FROM ubuntu

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        g++

# Use unique location to pull in project from local machine.
# We can mount over this location with our local version when
# using the docker run command to build this on the fly.
#
ARG PROJECT_SRC

ENV APP_LIBS /app/lib
ENv APP_BIN  /app/bin

RUN mkdir -p \
    ${PROJECT_SRC} \
    ${APP_LIBS} \
    ${APP_BIN}

COPY . ${PROJECT_SRC}

RUN    g++ -o ${APP_LIBS}/library.o -c -I${PROJECT_SRC}/include ${PROJECT_SRC}/src/library.cpp \
    && g++ -o ${APP_LIBS}/main.o    -c -I${PROJECT_SRC}/include ${PROJECT_SRC}/src/main.cpp \
    && g++ -o ${APP_BIN}/add ${APP_LIBS}/library.o ${APP_LIBS}/main.o

ENV PATH ${PATH}:${APP_BIN}

WORKDIR /

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["add"]
